services:
  mysql8:
    container_name: mysql8
    image: mysql:8.0.42
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=sasa1234
      - MYSQL_DATABASE=msvc_k8_users
    volumes:
      - mysql_data_k8:/var/lib/mysql
    restart: always
    networks:
      - springcloud  
  postgres-container:
    container_name:  postgres-container
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sasa
      - POSTGRES_DB=msvc-k8-courses
    volumes:
      - postgres_data_volume:/var/lib/postgresql/data
    restart: always
    networks:
      - springcloud
  msvc-k8-users:
    container_name: msvc-k8-users
    image: luisenriquesm/msvc-k8-users:v1
    ports:
      - "8001:8001"
    env_file: ./msvc-k8-users/.env
    networks:
      - springcloud
    depends_on:
      - mysql8
    restart: always

  msvc-k8-courses:
    container_name: msvc-k8-courses
    image: luisenriquesm/msvc-k8-courses:v1
    ports:
      - "8002:8002"
    env_file: ./msvc-k8-courses/.env
    networks:
      - springcloud
    depends_on:
      - postgres-container
      - msvc-k8-users
    restart: always

volumes:
  mysql_data_k8:
    name: mysql_data_k8
    external: true
  postgres_data_volume:
    name: postgres_data_volume
    external: true

networks:
  springcloud: