services:
  mysql8:
    container_name: mysql8
    image: mysql:8.0.42
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=sasa1234
      - MYSQL_DATABASE=msvc_k8_users
    volumes:
      - mysql_data_k8:/var/lib/mysql
    restart: always
    networks:
      - springcloud  
  postgres-container:
    container_name:  postgres-container
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sasa
      - POSTGRES_DB=msvc-k8-courses
    volumes:
      - postgres_data_volume:/var/lib/postgresql/data
    restart: always
    networks:
      - springcloud
  msvc-k8-users:
    container_name: msvc-k8-users
    image: luisenriquesm/msvc-k8-users:v2
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
      - DB_HOST=mysql8:3306
      - DB_DATABASE=msvc_k8_users
      - DB_USERNAME=root
      - DB_PASSWORD=sasa1234
      - COURSES_URL=msvc-k8-courses:8002 
    networks:
      - springcloud
    depends_on:
      - mysql8
    restart: always

  msvc-k8-courses:
    container_name: msvc-k8-courses
    image: luisenriquesm/msvc-k8-courses:v2
    ports:
      - "8002:8002"
    environment:
      - PORT=8002
      - DB_HOST=postgres-container:5432
      - DB_DATABASE=msvc-k8-courses
      - DB_USERNAME=postgres
      - DB_PASSWORD=sasa
      - USERS_URL=msvc-k8-users:8001
    networks:
      - springcloud
    depends_on:
      - postgres-container
      - msvc-k8-users
    restart: always

volumes:
  mysql_data_k8:
    name: mysql_data_k8
  postgres_data_volume:
    name: postgres_data_volume

networks:
  springcloud: