services:
  postgres-container:
    container_name:  postgres-container
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sasa
      - POSTGRES_DB=msvc-k8-courses
    volumes:
      - postgres_data_volume:/var/lib/postgresql/data
    restart: always
    networks:
      - springcloud

  msvc-k8-courses:
    container_name: msvc-k8-courses
    image: luisenriquesm/msvc-k8-courses:v2
    ports:
      - "8002:8002"
    environment:
      - PORT=8002
      - DB_HOST=postgres-container:5432
      - DB_DATABASE=msvc-k8-courses
      - DB_USERNAME=postgres
      - DB_PASSWORD=sasa
      - USERS_URL=ec2-3-83-152-144.compute-1.amazonaws.com:8001
    networks:
      - springcloud
    depends_on:
      - postgres-container
    restart: always

volumes:
  postgres_data_volume:
    name: postgres_data_volume

networks:
  springcloud: