services:
  mysql8:
    container_name: mysql8
    image: mysql:8.0.42
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=sasa1234
      - MYSQL_DATABASE=msvc_k8_users
    volumes:
      - mysql_data_k8:/var/lib/mysql
    restart: always
    networks:
      - springcloud  

  msvc-k8-users:
    container_name: msvc-k8-users
    image: luisenriquesm/msvc-k8-users:v2
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
      - DB_HOST=mysql8:3306
      - DB_DATABASE=msvc_k8_users
      - DB_USERNAME=root
      - DB_PASSWORD=sasa1234
      - COURSES_URL=ec2-44-204-71-89.compute-1.amazonaws.com:8002 
    networks:
      - springcloud
    depends_on:
      - mysql8
    restart: always
 
volumes:
  mysql_data_k8:
    name: mysql_data_k8

networks:
  springcloud: